spring:
  application:
    name: cloud-eureka #服务名称
  security:
    user:
      name: user    #配置登陆的账号-user
      password: 123     #密码-123
server:
  port: 9002 #端口
eureka:
  instance:
    hostname: localhost:${server.port} #实例注册地址
  client:
    #fetch-registry: false
    #register-with-eureka: false
    service-url:
      defaultZone: http://localhost:9000/eureka/  #注册的协议地址访问名称
  server:
    enable-self-preservation: false #关闭自我保护机制 eureka心跳默认为90s,当短时间内发生大量服务宕机,就会自动开启自我保护机制,
                                    #就会把宕机的服务删除掉,等网络恢复后,会自动关闭自我保护机制
