spring:
  application:
    name: cloud-redis #服务名称
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 20 #连接池最大连接数（使用负值表示没有限制）
        max-idle: 8   #连接池中的最大空闲连接
        min-idle: 5   # 连接池中的最小空闲连接
    timeout: 6000   #连接超时时长（毫秒）
server:
  port: 10010 #端口
eureka:
  instance:
    hostname: 127.0.0.1 #实例注册地址
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka,http://localhost:9002/eureka/